version: '3.8'

services:
  order_db:
    image: postgres
    ports:
      - "6666:5432"
    environment:
      POSTGRES_PASSWORD: changemeinprod!
    volumes:
      - postgres_data:/var/lib/postgresql/data
  inventory_db:
    image: postgres
    ports:
      - "6667:5432"
    environment:
      POSTGRES_PASSWORD: changemeinprod!
    volumes:
      - inventory_data:/var/lib/postgresql/data
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin_user
      - MONGO_INITDB_ROOT_PASSWORD=admin_password
      - MONGO_INITDB_DATABASE=product-service
    volumes:
      - mongodb_data:/data/db

volumes:
  postgres_data:
    name: postgres_data
  mongodb_data:
    name: mongodb_data
  inventory_data:
    name: inventory_data